### ISSUE TITLE
Stackoverflow when loading game

### ISSUE THREAD

**Issue by jan-christiansen** [flofe104/legislative-bargaining-lab#15]
After clicking on "Load current game" the application crashes with

`[Error] RangeError: Maximum call stack size exceeded.`

It seems that the error occurs in the `Decoder`, which transforms the JavaScript data type the represents the QOBDD into the corresponding Elm data type. The decoder probably does not terminate at all. Because the JavaScript data type is cycling, the Decoder uses the function `lazy` in order to prevent non-termination.

I am not sure why the code behaves differently now, we might have to check whether the code work before you applied the changes.

**Comment by florian-kohrs** [comment]
The error occurred due to outdated files. Fixed by copying the folder "closure-library", "js" and "jshashtable-2.1" from branch "gh-pages".

**Comment by jan-christiansen** [comment]
I was not able to execute the build script anymore. It looks like there was a non-displayable character that caused the problem. This probably happened because Windows uses two characters for breaking a line while mac and unix only use a single character.
