### ISSUE TITLE
Write Tests for buildRec 

### ISSUE THREAD

**Issue by florian-kohrs** [flofe104/legislative-bargaining-lab#18]
This package is used for testing: https://package.elm-lang.org/packages/elm-explorations/test/latest
Installation  and usage guide here:  https://github.com/rtfeldman/node-test-runner

**Comment by jan-christiansen** [comment]
Which steps do I have to perform to execute the tests?

**Comment by florian-kohrs** [comment]
To execute the tests do:
1. Run npm install -g elm-test if you haven't already
2. cd into the project's root directory that has your elm.json.
3. Run elm-test
